### ISSUE TITLE
Alfred fails to update itself

### ISSUE THREAD

**Issue by efredz** [Rankmi/alfred#76]
sudo alfred update                                                                                                                                                                                     
[sudo] contraseña para edgardo:
Github Username: efredzb@gmail.com
Github Password:
Traceback (most recent call last):
  File "main.py", line 79, in <module>
  File "site-packages/click/core.py", line 764, in __call__
  File "site-packages/click/core.py", line 717, in main
  File "site-packages/click/core.py", line 1137, in invoke
  File "site-packages/click/core.py", line 956, in invoke
  File "site-packages/click/core.py", line 555, in invoke
  File "main.py", line 51, in update
  File "services/githubservice.py", line 178, in update_binary
  File "services/githubservice.py", line 167, in get_last_release
TypeError: must be str, not NoneType
[9740] Failed to execute script main

**Comment by rodrigonp** [comment]
This is already solved in the latest release. For older versions you have to either update the binary by downloading it directly from the releases page or by setting your Github token via `alfred reset global`
